server:
  port: 12300
spring:
  application:
    name: equipment-web
  redis:
    host: ${REDIS_HOST:47.94.211.172}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:738788}
rpc:
  mode: true
  dubbo:
    module: equipment-web
<<<<<<< HEAD
#    registryAddress: 127.0.0.1:2181
#    registryAddress: ${ZOOKEEPER_HOST:127.0.0.1}:${ZOOKEEPER_PORT:2181}
=======
>>>>>>> master
    registryAddress: ${ZK_HOST:127.0.0.1}:${ZK_PORT:2181}
#    port: 20880

management.security.enabled: false
