spring:
  application:
    name: equipment-equipment-provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://${MYSQL_HOST:47.94.211.172}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:yankuang_equipment}?useUnicode=true&characterEncoding=UTF8
#    url: jdbc:mysql://${MYSQL_HOST:47.94.211.172}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:yankuang_equipment_test}?useUnicode=true&characterEncoding=UTF8
#    username: ${MYSQL_USERNAME:root}
#    password: ${MYSQL_PASSWORD:uAiqwVwjJ8-i}
    url: jdbc:mysql://${MYSQL_HOST:47.94.211.172}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:yankuang_equipment_pro}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=CTT&useSSL=false
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:uAiqwVwjJ8-i}
rpc:
  mode: true
  dubbo:
    module: equipment-equipment-provider
    registryAddress: ${ZOOKEEPER_HOST:47.94.211.172}:${ZOOKEEPER_PORT:2181}
    version: test_zhou
    port: 20881
#    port: 20880

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: >
    com.yankuang.equipment.equipment.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mapper:
  basePackage: com.yankuang.equipment.equipment.mapper
