spring:
  application:
    name: equipment-syslog-provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:47.94.211.172}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:yankuang_equipment}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=CTT&useSSL=false
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:uAiqwVwjJ8-i}
rpc:
  mode: true
  dubbo:
    module: equipment-syslog-provider
    registryAddress: ${ZOOKEEPER_HOST:127.0.0.1}:${ZOOKEEPER_PORT:2181}
    port: 20883
#    port: 20880

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: >
    com.yankuang.equipment.syslog.model

mapper:
  basePackage: com.yankuang.equipment.syslog.mapper
