spring:
  application:
    name: equipment-syslog-provider
  data:
    mongodb:
      uri: mongodb://kcx_001:kcx_001@60.205.210.117:27017/zt_user_role
      host: 60.205.210.117
      port: 27017
      username: kcx_001
      password: kcx_001

rpc:
  mode: true
  dubbo:
    module: equipment-syslog-provider
    registryAddress: ${ZOOKEEPER_HOST:47.94.211.172}:${ZOOKEEPER_PORT:2181}
    version: test_zhou
    port: 20883
#    port: 20880

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: >
    com.yankuang.equipment.syslog.model

mapper:
  basePackage: com.yankuang.equipment.syslog.mapper
