spring:
  application:
    name: equipment-leasing-provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.94.211.172:3306/yankuang_equipment?useUnicode=true&characterEncoding=UTF8
    username: root
    password: uAiqwVwjJ8-i

rpc:
  mode: true
  dubbo:
    module: equipment-leasing-provider
#    registryAddress: 127.0.0.1:2181
    registryAddress: ${ZK_HOST:127.0.0.1}:${ZK_PORT:2181}
    port: 20881

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: >
    com.yankuang.equipment.leasing.model

mapper:
  basePackage: com.yankuang.equipment.leasing.mapper
